all: simple_server simple_client simple_client1
simple_server: simple_server.c
	gcc -o simple_server simple_server.c
simple_client: simple_client.c
	gcc -o simple_client simple_client.c
simple_client1: simple_client.c
	gcc -o simple_client1 simple_client.c
